config/routes.rb
Rails.application.routes.draw do
  get '/home', to: 'pages#home'

#  get '/books', to: 'books#index'
#  get '/books/new', to: 'books#new', as: 'new_book'
#  post '/books', to: 'books#create'
#  get '/books/:id/edit', to: 'books#edit', as: 'edit_book'
#  patch '/books/:id', to: 'books#update'
#  get '/books/:id', to: 'books#show', as: 'book'
#  delete '/books/:id', to: 'books#destroy'

  resources :books
  resources :authors

  get '/login', to: 'logins#new'
  post 'login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'

  resources :borrowers, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ActiveRecord::Base
	has_many :books, dependent: :destroy
	validates :name, presence: true, length: { minimum: 3, maximum: 40 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :author
	validates :author_id, presence: true
	validates :name, presence: true, length: { minimum: 5, maximum: 100 }
	validates :description, presence: true, length: { minimum: 20, maximum: 500 }
end

app/models/borrower.rb
class Borrower < ActiveRecord::Base
	has_many :books
	validates :name, presence: true, length: { minimum: 3, maximum: 40 }
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	validates :name, presence:true, length: { minimum: 3, maximum: 40 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence:true, length: { maximum: 105 },
                                   uniqueness: { case_sensitive: false },
                                   format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to books_path
    end
  end 
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
	def index
		@authors = Author.all
	end

	def show
		@author = Author.find(params[:id])
		@books = @author.books
	end

	def new
		@author = Author.new
	end

	def create
		@author = Author.new(author_params)

		if @author.save
			flash[:success] = "Author was created successfully"
			redirect_to authors_path
		else
			render :new
		end
	end

	def edit
		@author = Author.find(params[:id])
	end

	def update
		@author = Author.find(params[:id])
		if @author.update(author_params)
			flash[:success] = "Author was updated successfully"
			redirect_to authors_path
		else
			render :edit
		end
	end

	def destroy
		Author.find(params[:id]).destroy
		flash[:success] = "Author was deleted successfully"
		redirect_to authors_path
	end

	private
		def author_params
			params.require(:author).permit(:name, :email)
		end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :require_user, except: [:show, :index]

	def index
		@books = Book.all
	end

	def show
		@book = Book.find(params[:id])
	end

	def new
		@book = Book.new
	end

	def create
		@book = Book.new(book_params)
		@book.author = Author.find(@book.author_id)

		if @book.save
			flash[:success] = "Book was created successfully"
			redirect_to books_path
		else
			render :new
		end
	end

	def edit
		@book = Book.find(params[:id])
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
			flash[:success] = "Book was updated successfully"
			redirect_to book_path(@book)
		else
			render :edit
		end
	end

	def destroy
		Book.find(params[:id]).destroy
		flash[:success] = "Book was deleted successfully"
		redirect_to books_path
	end

	private
		def book_params
			params.require(:book).permit(:name, :description, :author_id)
		end
end

app/controllers/borrowers_controller.rb
class BorrowersController < ApplicationController
	def show

	end

	def new
		@borrower = Borrower.new
	end

	def create

	end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  
  def new
    
  end
  
  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "You are logged in"
      redirect_to books_path
    else
      flash.now[:danger] = "Your email address or password does not match"
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to home_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/edit.html.erb
<%= render 'shared/page_title', title: "Edit Author" %>

<%= render 'shared/errors', obj: @author %>
<div class="row">
	<div class="well col-md-8 col-md-offset-2">
		<%= form_for @author do |f| %>
			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.submit "Edit Author", class: "btn btn-success" %>
		<% end %>	
	</div>
</div>

app/views/authors/index.html.erb
<div class="container">
  <h2 class="center">Authors Listing</h2>      
  <table class="table" style='table-layout:fixed;'>
    <thead>
      <tr>
        <th class="center">Author Name</th>
        <th class="center">Action</th>
      </tr>
    </thead>
    <tbody>
    <% @authors.each do |author| %>
      <tr class="center">
        <td><%= author.name %></td>
        <td>
					<%= link_to "View Books", author_path(author) %>
          <% if logged_in? %>
  					| <%= link_to "Edit", edit_author_path(author) %>
  					| <%= link_to "Delete", author, method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
        </td>
      </tr>
    <% end %>  
    </tbody>
  </table>
</div>

app/views/authors/new.html.erb
<%= render 'shared/page_title', title: "Create Author" %>

<%= render 'shared/errors', obj: @author %>
<div class="row">
	<div class="well col-md-8 col-md-offset-2">
		<%= form_for @author do |f| %>
			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.submit "Create Author", class: "btn btn-success" %>
		<% end %>	
	</div>
</div>

app/views/authors/show.html.erb
<div class="container">
  <h2 class="center"><%= "Books of " + @author.name %></h2> 
  <table class="table" style='table-layout:fixed;'>
    <thead>
      <tr>
        <th class="center">Book Name</th>
        <th class="center">Action</th>
      </tr>
    </thead>
    <tbody>
    <% @books.each do |book| %>
      <tr class="center">
        <td><%= book.name %></td>
        <td>
          <%= link_to "View", book_path(book) %>
          <% if logged_in? %>
            | <%= link_to "Edit", edit_book_path(book) %>
            | <%= link_to "Delete", book, method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
        </td>
      </tr>
    <% end %>  
    </tbody>
  </table>
</div>

app/views/books/_form.html.erb
<%= render 'shared/errors', obj: @book %>
<div class="row">
	<div class="well col-md-8 col-md-offset-2">
		<%= form_for @book do |f| %>
			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :description %>
			<%= f.text_area :description, rows: 10 %>

			<div class="field">
		    <%= f.label :author %><br>
		    <%= f.collection_select :author_id, Author.all, :id, :name %>
		  </div>

			<%= f.submit(@book.new_record? ? 'Create Book' : 'Edit Book', class: "btn btn-success") %>
		<% end %>	
	</div>
</div>

app/views/books/edit.html.erb
<%= render 'shared/page_title', title: "Edit Book" %>
<%= render "form" %>

app/views/books/index.html.erb
<div class="container">
  <h2 class="center">Books Listing</h2>      
  <table class="table" style='table-layout:fixed;'>
    <thead>
      <tr>
        <th class="center">Book Name</th>
        <th class="center">Author</th>
        <th class="center">Action</th>
      </tr>
    </thead>
    <tbody>
    <% @books.each do |book| %>
      <tr class="center">
        <td><%= book.name %></td>
        <td><%= book.author.name %></td>
        <td>
					<%= link_to "View", book_path(book) %>
          <% if logged_in? %>
  					<%= link_to "Edit", edit_book_path(book) %>
  					<%= link_to "Delete", book, method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
        </td>
      </tr>
    <% end %>  
    </tbody>
  </table>
</div>

app/views/books/new.html.erb
<%= render 'shared/page_title', title: "Create Book" %>
<%= render "form" %>

app/views/books/show.html.erb
<p>
	<h1 class="center"><%= @book.name %></h1>
	<h6 class="center">By: <%= @book.author.name %></h6>	
	<hr/>
</p>
<div class="row">
	<div class="well col-md-10 col-md-offset-1">	
		<%= simple_format(@book.description) %>
	</div>
</div>
<% if logged_in? %>
<%= link_to "Edit this Book", edit_book_path(@book), class: "btn btn-success pull-right" %>
<% end %>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-md-10">
		<% flash.each do |message_type, message| %>
			<div class="alert alert-<%= message_type %>"><%= message %>
				<a class="close" data-dismiss="alert">&#215;</a>
				</div>
		<% end %>
	</div>			
</div>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "Home", home_path, class: "nav_item" %>  
    <ul class="nav_item">
      <li class="dropdown">
        <%= link_to '#', class: "dropdown-toggle", "data-toggle" => "dropdown" do %>
        Modules <b class="caret"></b>
      <% end %>
      <ul class="dropdown-menu">
        <li><%= link_to "Books Listing", books_path %></li>
        <% if logged_in? %><li><%= link_to "Add Book", new_book_path %></li><% end %>
        <li class="divider"></li>
        <li><%= link_to "Authors Listing", authors_path %></li>
        <% if logged_in? %><li><%= link_to "Add Author", new_author_path %></li><% end %>
      </ul>
      </li>
    </ul>
    <% if logged_in? %>
      <ul class="nav_item">
        <li class="dropdown">
          <%= link_to '#', class: "dropdown-toggle", "data-toggle" => "dropdown" do %>
          Issue Books <b class="caret"></b>
        <% end %>
        <ul class="dropdown-menu">
          <li><%= link_to "Books Issued Listing", "" %></li>
          <li><%= link_to "Borrow Book", "" %></li>
        </ul>
        </li>
      </ul>
      <div class="nav_item dropdown pull-right">
        <ul class="dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          <%= link_to current_user.name %>
          <span class="caret"></span>          
        </ul>
        <ul class="dropdown-menu">
          <li><%= link_to "Logout", logout_path %></li>
        </ul>
    </div>
    <% else %>
      <div class="nav_item">
        <%= link_to "Login", login_path %>
      </div>
    <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Honesty</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>

   <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
   </div>   
  
  </body>
</html>

app/views/logins/new.html.erb
<%= render 'shared/page_title', title: 'Log in' %>

<div class="row">
  <div class="well col-md-6 col-md-offset-3">
    <%= form_tag '/login' do %>
      
      <%= label_tag :email %>
      <%= text_field_tag :email %>
      
      <%= label_tag :password %>
      <%= password_field_tag :password %> 
      
      <%= submit_tag 'Login', class: 'btn btn-success'%>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>Shield Foundry Library</h1>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="alert alert-danger col-md-8 col-md-offset-2">
      <h5>Please correct the following errors:</h5>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>  

app/views/shared/_page_title.html.erb
<p>
	<h1 class="center"><%= title %></h1>
	<hr/>
</p>